version: "3.9"

services:
  db:
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - dateguess

networks:
  dateguess:
    name: dateguess